// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
// // import { ConnectWallet } from "@thirdweb-dev/react";
// import courses from "../data/courses.json";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import Search from "@/components/Search";
// import ChatButton from "@/components/ChatButton";
// import SwipeableCourses from "@/components/SwipeableCourses";

// import { solveMathProblem } from "@/utils/gpt";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Edustar</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Navbar />
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className={styles.grid}>
//           <Search />
//         </div>
//         <SwipeableCourses courses={courses} />
//         <ChatButton />
//       </main>
//       <Footer />
//     </>
//   );
// }

import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import courses from "../data/courses.json";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Search from "@/components/Search";
import ChatButton from "@/components/ChatButton";
import SwipeableCourses from "@/components/SwipeableCourses";

const inter = Inter({ subsets: ["latin"] });

const coursesPerPage = 12;

export default function Home() {
  return (
    <>
      <Head>
        <title>Edustar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <Search />
        </div>
        <SwipeableCourses courses={courses} coursesPerPage={coursesPerPage} />
        <ChatButton />
      </main>
      <Footer />
    </>
  );
}
