import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import courses from "../data/courses.json";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Search from "@/components/Search";
import ChatButton from "@/components/ChatButton";
import SwipeableCourses from "@/components/SwipeableCourses";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const coursesPerPage = 12;

export default function Home() {
  const [searchResult, setSearchResults] = useState([]);
  const [allCourses, setAllCourses] = useState(courses);
  const [isTitleClicked, setIsTitleClicked] = useState(false);

  return (
    <>
      <Head>
        <title>Edustar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setIsTitleClicked={setIsTitleClicked} />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid}>
          <Search setSearchResults={setSearchResults} setIsTitleClicked={setIsTitleClicked} />
        </div>
        <SwipeableCourses courses={searchResult.length > 0 && !isTitleClicked ? searchResult : allCourses} coursesPerPage={coursesPerPage} />
        <ChatButton />
      </main>
      <Footer />
    </>
  );
}
