import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Quiz from "@/components/Quiz";
import Link from "next/link";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [showQuiz, setShowQuiz] = useState(false);

  const handleQuizClick = () => {
    setShowQuiz(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${inter.className}`}>
        {/* <div className={styles.grid}> */}
        <div className={styles.card} onClick={handleQuizClick}>
          <h2>Quiz &rarr;</h2>
          <p>Take a quiz to test your knowledge of the material.</p>
        </div>
        {showQuiz && <Quiz />}
        {/* </div> */}
      </main>
      <Footer />
    </>
  );
}
